CREATE TYPE "public"."user_role" AS ENUM('user', 'admin', 'superadmin');--> statement-breakpoint
DROP INDEX "household_member_unique_idx";--> statement-breakpoint
ALTER TABLE "accounts" ALTER COLUMN "current_balance_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "accounts" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "advisor_sessions" ALTER COLUMN "last_confirmed_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "advisor_sessions" ALTER COLUMN "last_decision_recompute" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "advisor_sessions" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "advisor_sessions" ALTER COLUMN "last_activity_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "alerts" ALTER COLUMN "scheduled_for" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "alerts" ALTER COLUMN "sent_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "alerts" ALTER COLUMN "read_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "alerts" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_runway" ALTER COLUMN "current_balance_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_runway" ALTER COLUMN "calculated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_runway" ALTER COLUMN "days_until_zero" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_runway" ALTER COLUMN "daily_burn_rate_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_runway" ALTER COLUMN "weekly_burn_rate_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_runway" ALTER COLUMN "upcoming_bills_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_runway" ALTER COLUMN "upcoming_bills_count" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_runway" ALTER COLUMN "safe_to_spend_today_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_runway" ALTER COLUMN "safe_to_spend_week_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_runway" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "categories" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "category_patterns" ALTER COLUMN "match_count" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "category_patterns" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "category_patterns" ALTER COLUMN "updated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "daily_forecasts" ALTER COLUMN "predicted_balance_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "daily_forecasts" ALTER COLUMN "confidence_interval_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "daily_forecasts" ALTER COLUMN "expected_income_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "daily_forecasts" ALTER COLUMN "expected_expenses_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "daily_forecasts" ALTER COLUMN "expected_bills_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "daily_forecasts" ALTER COLUMN "generated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "daily_forecasts" ALTER COLUMN "actual_balance_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "daily_summaries" ALTER COLUMN "current_balance_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "daily_summaries" ALTER COLUMN "cash_runway_days" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "daily_summaries" ALTER COLUMN "safe_to_spend_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "daily_summaries" ALTER COLUMN "yesterday_spent_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "daily_summaries" ALTER COLUMN "yesterday_earned_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "daily_summaries" ALTER COLUMN "bills_due_count" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "daily_summaries" ALTER COLUMN "bills_due_amount_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "daily_summaries" ALTER COLUMN "generated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "daily_summaries" ALTER COLUMN "sent_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "daily_summaries" ALTER COLUMN "opened_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "debt_payments" ALTER COLUMN "amount_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "debt_payments" ALTER COLUMN "principal_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "debt_payments" ALTER COLUMN "interest_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "debt_payments" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "debts" ALTER COLUMN "original_balance_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "debts" ALTER COLUMN "current_balance_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "debts" ALTER COLUMN "minimum_payment_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "debts" ALTER COLUMN "term_months" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "debts" ALTER COLUMN "due_day" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "debts" ALTER COLUMN "total_interest_projected_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "debts" ALTER COLUMN "danger_score" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "debts" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "debts" ALTER COLUMN "updated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "decision_state" ALTER COLUMN "primary_command_amount_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "decision_state" ALTER COLUMN "computed_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "decision_state" ALTER COLUMN "expires_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "decision_state" ALTER COLUMN "acknowledged_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "documents" ALTER COLUMN "file_size_bytes" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "documents" ALTER COLUMN "processed_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "documents" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "email_verification_tokens" ALTER COLUMN "expires_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "email_verification_tokens" ALTER COLUMN "used_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "email_verification_tokens" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "envelopes" ALTER COLUMN "budget_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "envelopes" ALTER COLUMN "spent_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "envelopes" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "file_imported_items" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "file_parsed_summaries" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "goals" ALTER COLUMN "target_amount_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "goals" ALTER COLUMN "current_amount_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "goals" ALTER COLUMN "recommended_monthly_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "goals" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "goals" ALTER COLUMN "updated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "goals" ALTER COLUMN "completed_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "household_invites" ALTER COLUMN "expires_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "household_invites" ALTER COLUMN "used_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "household_invites" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "household_members" ALTER COLUMN "user_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "household_members" ALTER COLUMN "invited_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "household_members" ALTER COLUMN "accepted_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "households" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "households" ALTER COLUMN "updated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "interview_sessions" ALTER COLUMN "started_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "interview_sessions" ALTER COLUMN "completed_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "interview_sessions" ALTER COLUMN "last_activity_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "monthly_snapshots" ALTER COLUMN "total_income_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "monthly_snapshots" ALTER COLUMN "total_spending_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "monthly_snapshots" ALTER COLUMN "net_savings_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "monthly_snapshots" ALTER COLUMN "danger_days_count" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "monthly_snapshots" ALTER COLUMN "overspend_days_count" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "monthly_snapshots" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "monthly_snapshots" ALTER COLUMN "updated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "oauth_connections" ALTER COLUMN "expires_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "oauth_connections" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "oauth_connections" ALTER COLUMN "updated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "password_reset_tokens" ALTER COLUMN "expires_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "password_reset_tokens" ALTER COLUMN "used_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "password_reset_tokens" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "recurring_transactions" ALTER COLUMN "expected_amount_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "recurring_transactions" ALTER COLUMN "day_of_month" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "recurring_transactions" ALTER COLUMN "day_of_week" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "recurring_transactions" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "recurring_transactions" ALTER COLUMN "updated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sessions" ALTER COLUMN "expires_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sessions" ALTER COLUMN "revoked_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sessions" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "spending_patterns" ALTER COLUMN "day_of_week" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "spending_patterns" ALTER COLUMN "week_of_month" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "spending_patterns" ALTER COLUMN "avg_spending_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "spending_patterns" ALTER COLUMN "median_spending_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "spending_patterns" ALTER COLUMN "max_spending_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "spending_patterns" ALTER COLUMN "sample_count" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "spending_patterns" ALTER COLUMN "updated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "subscriptions" ALTER COLUMN "amount_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "subscriptions" ALTER COLUMN "start_date" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "subscriptions" ALTER COLUMN "end_date" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "subscriptions" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "subscriptions" ALTER COLUMN "updated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "transaction_inbox" ALTER COLUMN "raw_amount_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "transaction_inbox" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "transaction_inbox" ALTER COLUMN "reviewed_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "transactions" ALTER COLUMN "amount_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "transactions" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "transactions" ALTER COLUMN "updated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "uploaded_files" ALTER COLUMN "size_bytes" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "uploaded_files" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "uploaded_files" ALTER COLUMN "updated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "user_profiles" ALTER COLUMN "onboarding_step" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "user_profiles" ALTER COLUMN "monthly_salary_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "user_profiles" ALTER COLUMN "monthly_savings_goal_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "user_profiles" ALTER COLUMN "emergency_fund_goal_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "user_profiles" ALTER COLUMN "daily_spending_limit_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "user_profiles" ALTER COLUMN "weekly_spending_limit_cents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "user_profiles" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "user_profiles" ALTER COLUMN "updated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "email_verified_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "plan_expires_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "created_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "updated_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "last_login_at" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "household_members" ADD COLUMN "name" text;--> statement-breakpoint
ALTER TABLE "transactions" ADD COLUMN "sensitive" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "role" "user_role" DEFAULT 'user' NOT NULL;